sonar.organization=kuka-ros
sonar.projectName=kuka_external_control_sdk
sonar.projectKey=kuka-ros_kuka_external_control_sdk

sonar.host.url=https://sonarcloud.io

# only the core SDK is analysed
# sonar.modules entry is omitted to avoid module-relative path issues
sonar.sources=./kuka_external_control_sdk_common,./kuka_external_control_sdk_iiqka2

# do not analyse example code or tests
sonar.exclusions=**/test/**,**/tests/**,**/mxAutomation.h,**/plciec.h
# prevent duplication metrics from counting excluded files
sonar.cpd.exclusions=**/test/**,**/tests/**,**/mxAutomation.h,**/plciec.h

# Encoding and language settings
sonar.sourceEncoding=UTF-8
sonar.python.version=3
