sonar.host.url=https://sonarcloud.io
sonar.organization=kuka-ros
sonar.projectKey=kuka-ros_kuka_external_control_sdk
sonar.sources=kuka_external_control_sdk_common,kuka_external_control_sdk_iiqka2
sonar.exclusions=**/build/**,**/*.png,**/test/**,**/mxAutomation.h,**/plciec.h
sonar.cpd.exclusions=**/test/**,**/mxAutomation.h,**/plciec.h
sonar.sourceEncoding=UTF-8
