<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>kuka_external_control_sdk_common</name>
  <version>2.0.0</version>
  <description>Common utilities for the KUKA external control SDK</description>
  <maintainer email="tamas.pepo@kuka.com">Tamas Pepo</maintainer>
  <maintainer email="aron.svastits@kuka.com">Aron Svastits</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>cmake</buildtool_depend>

  <depend>libssl-dev</depend>

  <exec_depend>ament_cmake</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
