name: CI Debian

on:
  push:
    branches:
      - master
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        debian_version: [bookworm]
    container:
      image: debian:${{ matrix.debian_version }}

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        #!/bin/bash
        apt update && apt install -y cmake build-essential pkg-config libssl-dev libgtest-dev libtinyxml2-dev

    - name: Build and install common SDK
      run: mkdir -p build && cd build && cmake -DBUILD_TESTING=0 .. && make install
      working-directory: ./kuka_external_control_sdk_common

    - name: Build and install iiQKA2 SDK
      run: mkdir -p build && cd build && cmake -DBUILD_TESTING=1 .. && make install
      working-directory: ./kuka_external_control_sdk_iiqka2

    - name: Run iiQKA2 tests
      run: ./test_iiqka2_message_builder
      working-directory: ./kuka_external_control_sdk_iiqka2/build
