name: CI Fedora

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fedora_version: [38, 39]
    container:
      image: fedora:${{ matrix.fedora_version }}

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        #!/bin/bash
        dnf install -y cmake gcc-c++ openssl-devel gtest-devel tinyxml2-devel

    - name: Build and install common SDK
      run: cmake -DBUILD_TESTING=0 .. && make install
      working-directory: ./kuka_external_control_sdk_common/build

    - name: Build and install iiQKA2 SDK
      run: cmake -DBUILD_TESTING=1 .. && make install
      working-directory: ./kuka_external_control_sdk_iiqka2/build

    - name: Run iiQKA2 tests
      run: ./test_iiqka2_message_builder
      working-directory: ./kuka_external_control_sdk_iiqka2/build
